### ISSUE TITLE
[logic layer] error with logic layer call that works with regular tesseract

### ISSUE THREAD

**Issue by jspeis** [tesseract-olap/tesseract#138]
Vanilla Tesseract:
https://cny-dog.datawheel.us/tesseract/cubes/Syracuse%20City%20School%20District%20All%20Tables/aggregate?drilldowns[]=Year.Year.Year&measures[]=Chronic%20Absenteeism%20Rate%20All%20Students

LL Tesseract:

https://cny-dog.datawheel.us/tesseract/data?cube=Syracuse%20City%20School%20District%20All%20Tables&drilldowns=Year&measures=Chronic%20Absenteeism%20Rate%20All%20Students

Gives `Error Code 555`

any ideas what might cause this @MarcioPorto ?

**Comment by hwchen** [comment]
Logic layer requires that all levels are unique. You may be running up against this because there are repeating levels in the geography dim.

**Comment by jspeis** [comment]
@hwchen I don't think that is the issue I simplified the cube to this schema (below) and still get the 555 error in the LL.

```xml
  <Cube name="Syracuse City School District All Tables">
    <Table name="scsd_alltables"/>

    <Dimension foreign_key="dim_year" name="Year">
      <Hierarchy name="Year" primary_key="dim_year">
        <Level name="Year" key_column="dim_year" />
      </Hierarchy>
    </Dimension>

    <Measure name="Kindergarten Readiness Rates All Students" column="mea_aimsweb_pass_rate_k" aggregator="avg" />
    <Measure name="Kindergarten Readiness Rates Students in Poverty" column="mea_aimsweb_pass_rate_k_pov" aggregator="avg" />

    <Measure name="Chronic Absenteeism Rate All Students" column="mea_chronic_absenteeism" aggregator="avg" />
    <Measure name="Chronic Absenteeism Rate Students in Poverty" column="mea_chronic_absenteeism_pov" aggregator="avg" />

    <Measure name="Ela Grade 3 Pass Rate All Students" column="mea_ela_pass_rate_grade_3" aggregator="avg" />
    <Measure name="Ela Grade 3 Pass Rate Students in Poverty" column="mea_ela_pass_rate_grade_3_pov" aggregator="avg" />

    <Measure name="Percent Summer Learning Loss All Students" column="mea_pct_sll" aggregator="avg" />
    <Measure name="Percent Summer Learning Loss Students in Poverty" column="mea_pct_sll_pov" aggregator="avg" />

  </Cube>
```

**Comment by hwchen** [comment]
Interesting. That error code is associated with having non-unique levels though. I'll wait for @MarcioPorto to weigh in before investigating further.

**Comment by MarcioPorto** [comment]
Hum, I don't really know what's going on here. Would have to look at the logs @jspeis

**Comment by MarcioPorto** [comment]
@jspeis I believe this has been resolved, right? Can I close this issue?
