### ISSUE TITLE
v0.2 misc issues

### ISSUE THREAD

**Issue by hwchen** [tesseract-olap/tesseract#15]
- [ ] support unique/non-unique. Non-unique means that the drilldown cols must contain all parents, but only show the level selected.
- [ ] add support for sql fact and dim tables columns that have same name (using aliases)
- [x] remove hack for MemberType hardcoded when transitioning from dimensionusage to dimension in schema. Also, figure out a better way to get type data for members for cut.
- [ ] remove hack for inline tables, where fact table is handed to drillsql and cutsql, but they transfer through primary key and foreign key which are unused.
- [x] faster json serialization, keep order.
- flush (using rw lock)

**Comment by hwchen** [comment]
Membertype is now key type on levels

**Comment by hwchen** [comment]
Maybe don’t need flush. There’s no cache, and for schema changes you’re already on server.

**Comment by jspeis** [comment]
@hwchen can we close this one out and roll any outstanding issues here into the general SQL refactor issue?

**Comment by hwchen** [comment]
yup
