### ISSUE TITLE
[logic layer] Add parents, children and neighbors helper endpoints

### ISSUE THREAD

**Issue by MarcioPorto** [tesseract-olap/tesseract#172]

**Comment by hwchen** [comment]
- [ ] onboard mauricio to tesseract server
- [ ] write routing to handlers, and url interface (with walther)
- [ ] insert logic for handling relations (with marcio)

**Comment by jspeis** [comment]
@MarcioPorto can this be closed?

**Comment by hwchen** [comment]
this one is still in progress

**Comment by MarcioPorto** [comment]
Perhaps we can move it back to the todo swimlane for now? Unless @innerstage is working on it this week.

**Comment by MarcioPorto** [comment]
Fixed as of https://github.com/tesseract-olap/tesseract/commit/f537c357815a47d8a77399ac00517ea3ddf7b31a
