### ISSUE TITLE
Check readonly in database

### ISSUE THREAD

**Issue by hwchen** [tesseract-olap/tesseract#192]
Check that the database session is in readonly mode. Should be done on server startup, and either fail or warn (this behavior tbd).

An example db query to find the session state:
```
mochi :) select * from system.settings where name = 'readonly'
```
docs: https://clickhouse.yandex/docs/en/operations/settings/permissions_for_queries/

Part of robustness issue: #166

**Comment by jspeis** [comment]
going to close in favor of #205 for now
