### ISSUE TITLE
members endpoint don't work if locale parameter is set to "en"

### ISSUE THREAD

**Issue by frabarz** [tesseract-olap/tesseract#193]
Tthe new members endpoint doesn't support mapping `locale=en` to the default captions.

This URL works:  
https://api.datamexico.org/tesseract/members?cube=sesnsp_crimes&level=Affected+Legal+Good

But this one doesn't:  
https://api.datamexico.org/tesseract/members?cube=sesnsp_crimes&level=Affected+Legal+Good&locale=en

**Comment by jspeis** [comment]
fix has been merged to master
