### ISSUE TITLE
[relations] parents not working for "Location" level

### ISSUE THREAD

**Issue by jhmullen** [tesseract-olap/tesseract#228]
@MarcioPorto Provided me with the following example of a Municipality parent crawl-up:

https://api.datamexico.org/tesseract/relations.jsonrecords?cube=inegi_enigh_population&Municipality=14039:parents

However the endpoint does not seem to work for the lower Geography, `Location`:

https://api.datamexico.org/tesseract/relations.jsonrecords?cube=inegi_enigh_population&Location=100050724:parents

**Comment by MarcioPorto** [comment]
@jhmullen That cube you were using did not have a Location level, but this cube does: https://api.datamexico.org/tesseract/relations.jsonrecords?cube=inegi_denue&Location=100050724:parents

**Comment by jhmullen** [comment]
Any cube that a user uses to create a dimension in the first place will necessarily contain all levels that the parent endpoint would use. This was my mistake for using a random cube instead of the one set in datamexico (`inegi_population`, which works).
