### ISSUE TITLE
block the Password from getting logged on the Console

### ISSUE THREAD

**Issue by Jayrmajithia** [tesseract-olap/tesseract#239]

**Comment by jspeis** [comment]
update: turns out this is maybe actually be an issue in clickhouse-rs driver

**Comment by MarcioPorto** [comment]
Based on the conversation from the ClickHouse driver repo, we need to upgrade `clickhouse-rs` from https://github.com/tesseract-olap/tesseract/blob/master/tesseract-clickhouse/Cargo.toml to v0.1.19

**Comment by jspeis** [comment]
yup should be straightforward at this point now that the driver was updated

**Comment by MarcioPorto** [comment]
Closing since it seems like `clickhouse-rs` is already on 0.1.19 in https://github.com/tesseract-olap/tesseract/blob/master/tesseract-clickhouse/Cargo.toml#L8

**Comment by jspeis** [comment]
Yup thanks for closing this one out!
