### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by hwchen** [tesseract-olap/tesseract#50]
Would like to package for easier installs (especially when spinning up new servers).

First step is probably just creating a `.deb` using something like https://github.com/mmstick/cargo-deb and putting it in releases. (Would also install with `.service`)

After that I don't know if there's particular needs for distribution. Homebrew might be an option for OSX, and a ppa might be convenient for ubuntu.

**Comment by MarcioPorto** [comment]
@hwchen Should we close this?

**Comment by hwchen** [comment]
yes :)
